### ISSUE TITLE
I'd like to have the whole generated source folder deleted before running the generation task

### ISSUE THREAD

**Issue by elect86** [jjohannes/gradle-demos#1]
As titled, I'm kinda following your sample for several projects ([example](https://github.com/kotlin-graphics/kool/blob/master/buildSrc/src/main/kotlin/kool/gen/GenerateCode.kt)) and it happens that sometimes I rename a file and I have to (remember to) manually delete the previous generated sources in order to not have issues..

I'd like to have this step automatically always executed before generating the new sources.. 

I asked a couple of times on Slack, but never got something valuable..

What's the best way to achieve this?

**Comment by jjohannes** [comment]
Hi @elect86. Hope you are doing well.

I hope I understand the question correctly, but what I would do is deleting the folder in the beginning of the task action using Gradle's `FileOperations` service. In you example:


```
@get:Inject
abstract val files: FileSystemOperations

@TaskAction
fun generate() {
    files.delete { 
        it.delete(targetDir)
    }

    val target = targetDir.get().asFile
    ...
```

Hope this helps.

**Comment by elect86** [comment]
Thanks, I hope you are fine as well :)

The snippet seems to be working nice, thanks

One last wish: If I modify the generation sources and ran the tests, I'd like Gradle to execute automatically first the generation task and only later running the test. Is that possible?

**Comment by jjohannes** [comment]
If the code that you are generating is part of the test code, you can register the generate task as `srcDir` for the test source set. Then Gradle will run it before and also compile the generated code as part of the test code:

```
sourceSets.test {
    java.srcDir(generateCode) // 'generateCode' is a task with an output directory containing (Java) sources
}
```

Not sure if this is exactly you case. But maybe it helps to give you the right idea. 

Looks like you are doing something like that already though 🤔 
https://github.com/kotlin-graphics/kool/blob/b73b365c1b239cc4af493d535363cdd3e0fbef92/build.gradle.kts#L36-L37

**Comment by elect86** [comment]
For some reason it wasn't working, now it does, no idea

Anyway, another question: if I'd like to have the generated sources committed on git, what's the best practise out there? Adding `build/generated` to `.gitignore`? Or generate them under another location, such as `src/main/gen`?

**Comment by jjohannes** [comment]
I would put the files somewhere outside of `build`. Something like `src/main/gen` sounds good to me.

**Comment by elect86** [comment]
I'm experimenting right now with `src/main/kotlinGen`

then nice touch is that:
-  you don't get anymore the `[main]` tag on the old `mainGen` directory
- `kotlinGen` directory gets automatically recognized by Idea (showed as blue) 
- one less higher indentation step, code source more compact

I hope this won't break any optimization mechanism :)
